name: build-binary

on:
  push:
    branches: 'main'

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"
      - name: Build Binaries for Linux/MacOS
        run: |
          make
      - name: Sign Binaries
        working-directory: ./bin
        run: |
          gpg --armor --detach-sign helloworld
      - name: Verify Binaries
        working-directory: ./bin
        run: |
          gpg --verify helloworld.asc helloworld
